name: university_enrollment
description: A simple university enrollment system without a database.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

  # Add other packages below as needed

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true